### ISSUE TITLE
Moving from Google Code Wiki to GitHub Wiki

### ISSUE THREAD

**Issue by vsch** [siddii/scriptmonkey#13]
@siddii, I don't think you will mind but I started a GitHub Wiki for the plugin and would like to move the Google Code Wiki into these pages. I also added the Wiki as a submodule to the repository. It is easier for me to edit the pages in my [MuliMarkdown plugin](https://github.com/vsch/idea-multimarkdown) right in the scriptmonkey project in IntelliJ than to jump between the IDE and the browser.

For now I am keeping the submodule in develop branch but the Wiki's only have the master branch and the initial pages are already available: Home, Installation, Troubleshooting, Changing Boot JDK. I will be adding the Google Code Wiki pages so that these can be easily maintained. Hoping that other enthusiasts will be found who can help but someone had to get the ball rolling, like me. :)

**Comment by siddii** [comment]
No, not at all. Go for it :+1:

**Comment by vsch** [comment]
Done.
