### ISSUE TITLE
ScriptEngine does not load in IntelliJ IDEA 14.0

### ISSUE THREAD

**Issue by hellerim** [siddii/scriptmonkey#7]
This error shows up after the upgrade to IntelliJ IDEA 14.0:
com.boxysystems.scriptmonkey.intellij.ScriptMonkeyPlugin@7a60c9: cannot load JavaScript engine
Java version is 1.8.0_25 b18 x86

Code was taken from Apress "Pro Xml Development with Java Technology", Chapter 10.

**Comment by siddii** [comment]
Sorry, it took a while. Script Monkey v1.1 is compatible with Nashorn scripting engine (JDK8 & Intellij v14)

![screen shot 2015-04-27 at 9 55 10 pm](https://cloud.githubusercontent.com/assets/326472/7361987/383976b2-ed28-11e4-88f0-3ed478ea2847.png)
